Title = "Tharindu.dev"
baseurl = "https://tharindu.dev"
languageCode = "en-us"
title = "Tharindu N."
theme = "hello-friend-ng-mod"

[params]
  author = "Tharindu"
  homeSubtitle = "Just a dot."
  avatarurl = "https://i.imgur.com/IQQzoig.jpg"
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  keywords = "homepage, blog programming"
  contentTypeName = "posts"
  defaultTheme = "dark"
  copyright = "Copyrights Reserved. tharindu.dev"
  [params.logo]
    logoText     = "$ Tharindu.dev"
    logoHomeLink = "/"
[languages]
    [languages.en]
      subtitle  = ""
      weight    = 1
      copyright = 'Tharindu N.'
[menu]
  [[menu.main]]
    name = "contact"
    weight = 0
    url = "/contact"
  [[menu.main]]
    name = "posts"
    weight = 4
    url = "/posts"
  [[menu.main]]
    name = "about me"
    weight = 1
    url = "/about"
[[params.social]]
      name = "GitHub"
      icon = "fab fa-github fa-2x"
      url = "https://github.com/truethari"
[[params.social]]
      name = "Instagram"
      icon = "fab fa-instagram fa-2x"
      url = "#"
[[params.social]]
      name = "Keybase"
      icon = "fab fa-keybase fa-2x"
      url = "#"
[[params.social]]
      name = "DEV.to"
      icon = "fab fa-dev fa-2x"
      url = "https://dev.to/truethari"
[[params.social]]
      name = "GPG"
      icon = "fas fa-key fa-2x"
      url = "#"
